on:
  schedule:
    - cron: "50 23 * * *"
  workflow_dispatch:

jobs:
  j1:
    name: masterclass-reach
    runs-on: ubuntu-22.04
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: sayantikabanik/Masterclass
          ghtoken: ${{ secrets.ghrs_github_api_token }}
